name: 'lfg-be-development-database'

services:
  lfg-rdb:
    container_name: lfg-rdb
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
  lfg-cache:
    container_name: lfg-cache
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
