name: publish-server-types

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Types
        run: yarn run build:types

      - name: Convert lockfile
        run: yarn synp --source-file yarn.lock

      - name: Replace package.json
        run: |
          rm -rf node_modules
          rm -f package.json
          rm -f yarn.lock
          mv package.export.json package.json

      - name: Install Dependencies from npm
        run: npm ci

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
